name: tingle
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

#  STATE MANAGEMENT
  get: ^4.6.6

#  LOCAL STORAGE
  get_storage: ^2.1.1

# CONNECTION CHECK
  connectivity_plus: ^6.1.3

# GET PERMISSION
  permission_handler: ^11.4.0
  image_picker: ^1.1.2

#  FIREBASE PACKAGES
  firebase_core: ^3.11.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.4.2
  firebase_messaging: ^15.2.2
  device_info_plus: ^11.3.0

#  VIDEO RELATED
  camera: ^0.11.1
  video_player: ^2.9.2
  chewie: ^1.8.5
  get_thumbnail_video: ^0.7.3
  deepar_flutter_plus: ^0.2.0
  preload_page_view: ^0.2.0
  audioplayers: ^6.2.0

#  ffmpeg_kit_flutter: ^6.0.3
#  FFMPEG ALTERNATIVE
  retrytech_plugin:
    git:
      url: https://gitlab.com/jeelkhokhariya59/retrytech_plugin.git
      ref: master

# API CALLING
  http: ^1.3.0
  dio: ^5.8.0+1

# AUTHENTICATION
  flutter_otp_text_field: ^1.5.1+1

# COMMON PACKAGES
  intl: ^0.20.2
  fluttertoast: ^8.2.11
  readmore: ^3.0.0
  share_plus: ^10.1.4
  vibration: ^3.1.3
  blurrycontainer: ^2.1.0
  cached_network_image: ^3.4.1
  flutter_svga:
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  animated_flip_counter: ^0.3.4
  dots_indicator: ^4.0.1
  text_scroll: ^0.2.0
  fading_edge_scrollview: ^4.1.1
  marquee: ^2.2.3
  intl_phone_field: ^3.2.0
#  marquee: ^2.2.3
  country_picker: ^2.0.27


  #  LIVE RELATED
  socket_io_client: ^3.0.2
  agora_rtc_engine: ^6.5.0


#  LIST ANIMATION
  flutter_staggered_animations: ^1.1.1

#  BACKGROUND SERVICES
  flutter_isolate: ^2.1.0

#  NOTIFICATION
  flutter_local_notifications: ^18.0.1

# BRANCH IO
  flutter_branch_sdk: ^7.3.0

# WEB_VIEW (PRIVACY POLICY/GAME)
  webview_flutter: ^4.11.0

#  PAYMENT METHOD
  flutterwave_standard:
  #flutter_stripe: ^11.4.0
  flutter_stripe: ^10.2.0
  razorpay_flutter: ^1.4.0
  in_app_purchase: ^3.2.0
  in_app_purchase_android: any
  in_app_purchase_storekit: any

  date_picker_plus: ^4.2.0




  path_provider: any

  lottie: ^3.3.1

  dotted_border: ^2.1.0

#  workmanager: ^0.5.2





#  QR CODE (SHARE PROFILE)
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.0
  screenshot: ^3.0.0

# STOP SCREEN SHORT
  secure_application: ^4.1.0
  gallery_saver_plus: ^3.2.4
  url_launcher: ^6.3.1
  record: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_color: ^2.1.0
#  animate_do: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: lib/assets
  line_length: 80

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/music/
    - assets/effects/
    - assets/json/
    - assets/lottie/
    - assets/frames/

  fonts:


    - family: InterLight
      fonts:
        - asset: assets/fonts/Inter_28pt-Light.ttf

    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf

    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter_28pt-Medium.ttf

    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf

    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter_28pt-Bold.ttf

    - family: InterExtraBold
      fonts:
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf



